<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
/** @var \Magento\Contact\Block\ContactForm $block */
?>
<form class="form contact"
      action="<?= $block->escapeUrl($block->getFormAction()) ?>"
      id="contact-form"
      method="post"
      data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>"
      data-mage-init='{"validation":{}}'>
    <fieldset class="fieldset">
        <h2 class="contact-title text-center"><?= $block->escapeHtml(__('Get In Touch')) ?></h2>
        <div class="row">
            <div class="col-12 col-md-6 field name required">
                <div class="control">
                    <input name="name" id="name-contact" title="<?= $block->escapeHtmlAttr(__('Name')) ?>" placeholder="<?= $block->escapeHtmlAttr(__('Name')) ?>"
                           value="<?= $block->escapeHtmlAttr($this->helper('Magento\Contact\Helper\Data')->getPostValue('name') ?: $this->helper('Magento\Contact\Helper\Data')->getUserName()) ?>"
                           class="input-text" type="text" data-validate="{required:true}"/>
                </div>
            </div>
            <div class="col-12 col-md-6 field email required">
                <div class="control">
                    <input name="email" id="email-contact" title="<?= $block->escapeHtmlAttr(__('Email')) ?>" placeholder="<?= $block->escapeHtmlAttr(__('Email')) ?>"
                           value="<?= $block->escapeHtmlAttr($this->helper('Magento\Contact\Helper\Data')->getPostValue('email') ?: $this->helper('Magento\Contact\Helper\Data')->getUserEmail()) ?>"
                           class="input-text" type="email" data-validate="{required:true, 'validate-email':true}"/>
                </div>
            </div>
            <div class="col-12 field telephone">
                <div class="control">
                    <input name="telephone" id="telephone-contact"
                           title="<?= $block->escapeHtmlAttr(__('Phone Number')) ?>"
                           placeholder="<?= $block->escapeHtmlAttr(__('Phone Number')) ?>"
                           value="<?= $block->escapeHtmlAttr($this->helper('Magento\Contact\Helper\Data')->getPostValue('telephone')) ?>"
                           class="input-text" type="text"/>
                </div>
            </div>
            <div class="col-12 field comment required">
                <div class="control">
                    <textarea name="comment" id="comment-contact"
                              title="<?= $block->escapeHtmlAttr(__('Message')) ?>" placeholder="<?= $block->escapeHtmlAttr(__('Message')) ?>" class="input-text"
                              style="width: 100%;" rows="10"
                              data-validate="{required:true}"><?= $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getPostValue('comment')) ?></textarea>
                </div>
            </div>
        </div>
        <?= $block->getChildHtml('form.additional.info') ?>
        <div class="actions-toolbar">
            <div class="primary">
                <input type="hidden" name="hideit" id="hideit" value=""/>
                <button type="submit" title="<?= $block->escapeHtmlAttr(__('Send Message')) ?>" class="action submit primary">
                    <span><?= $block->escapeHtml(__('Submit')) ?></span>
                </button>
            </div>
        </div>
    </fieldset>
</form>
<div class="google-map"><!--    <script src="https://maps.googleapis.com/maps/api/js?v=3.exp&amp;key=AIzaSyCbeYth3ZUsoq3B0xsD3b7BmukI2Mgl6Wo" type="text/javascript" xml="space"></script>
  <div id="gmap_canvas" style="height: 600px; width: 100%;"></div>
  <script type="text/javascript" xml="space">// <![CDATA[
    function init_map(){var myOptions = {zoom:14,center:new google.maps.LatLng(52.342811, 4.815897),mapTypeId: google.maps.MapTypeId.TERRAIN};map = new google.maps.Map(document.getElementById('gmap_canvas'), myOptions);marker = new google.maps.Marker({map: map,position: new google.maps.LatLng(52.342811, 4.815897)});infowindow = new google.maps.InfoWindow({content:'<h2>Martfury</h2><p>Bastenakenstraat 58, 1066 JD Amsterdam,<br>Netherlands</p><strong><a href="https://www.google.com/maps/dir/?api=1&origin=your+location&destination=52.342811,4.815897">Get Direction</a></strong>'});google.maps.event.addListener(marker, 'click', function(){infowindow.open(map,marker);});infowindow.open(map,marker);}google.maps.event.addDomListener(window, 'load', init_map);
    // ]]></script> --> <iframe style="height: 405px; width: 100%;" src="https://www.google.com/maps/d/embed?mid=1QmHHaGvHYkmvpydfto3q5RAUYBs" width="300" height="150"></iframe></div>
