<?php
/**
 * @category  Webkul
 * @package   Webkul_Quotesystem
 * @author    Webkul
 * @copyright Copyright (c) Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */
?>
<style type="text/css">
    <?php if ($block->isSortData()) { ?>
        #wk_quotesystem_products {
            display: block !important;
        }
        #sales_order_create_customer_grid {
            display: none;
        }
    <?php } ?>
</style>