<?php //if($this->helper('Custom\City\Helper\Data')->getConfig('city/general/enabled')){?>
    <?php $url = $this->getUrl('city/index/cities');
    $city_link = '';
    $city_title = 'City not in list';
    //if($this->helper('Custom\City\Helper\Data')->getConfig('city/general/citynotinlist')){
        $city_link = 'enabled';
        //if($this->helper('Custom\City\Helper\Data')->getConfig('city/general/citynotinlist_title')!=""){
            $city_title = $this->helper('Custom\City\Helper\Data')->getConfig('city/general/citynotinlist_title');
        //}
    //}
    ?>
    <?php
    $curl = $this->getUrl('*/*/*', ['_current' => true, '_use_rewrite' => true]);
    if(strpos($curl,'checkout')!==false){
        $page = 'checkout';
    }//else{
        //$page = 'edit';
    //}?>
    <script type="text/javascript">
        var data_city_link="<?php echo $city_link;?>";
        var data_city_title="<?php echo $city_title;?>";
        var data_url="<?php echo $url;?>";
        var loading_url = "<?php echo $this->getViewFileUrl('Custom_City::images/loader-1.gif');?>";
        var nearStoreUrl = '<?php echo $block->getUrl('storepickup/storeholiday/neareststores'); ?>';
        <?php //if($page=='checkout'){?>
        require(["jquery","domReady!"], function($){
            <?php //if(strpos($curl,'cart')!==false){?>
            // if(jQuery('#shipping-zip-form').length==0){
            //     console.log('inside cart page-->>');
            //     setTimeout(function(){ shippingmainCityCart();}, 2000);
            // }
            <?php //}else{?>
            setTimeout(function(){ shippingmainCityCall();}, 3000);
            if(jQuery("input[type='submit']").length==0){
                setTimeout(function(){ checkSubmitButtonLoad();}, 1000);
            }
            <?php //}?>
        });
        function checkSubmitButtonLoad(){
            if(jQuery('.button').length==0){
                setTimeout(function(){ checkSubmitButtonLoad();}, 1000);
            }
            jQuery('.button').click(function(){
               bilingmainCityCall();
            });
        }
        <?php //}else{?>
        // require(["jquery","domReady!"], function($){
        //     setTimeout(function(){ addressPageCall();}, 2000);
        // });
        <?php //}?>
    </script>

<?php //}?>

